spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: tjwlsdl1
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBQ
    tokenExpiry: 8640000000000
    refreshTokenExpiry: 8640000000000

logging:
  level:
    root: info
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
