
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/user
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: tjwlsdl1
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 'ba5032125fbe89c9caa624e0088dd297'
            client-secret: 'd4VvaEIa85wAuD5mfBEtHN7n0tcNJiSA'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - birthday
            client-name: Kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
  application:
    name: user-service


jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOda'

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600


app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBA
    tokenExpiry: 604800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
logging:
  level:
    root: info
server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka